- name: Install vault
  when: enable_hashicorp_vault_cli | default(false)
  block:
    - name: add hashicorp apt repo
      ansible.builtin.include_role:
        name: hashicorp_apt_repo

    - name: install vault
      become: true
      ansible.builtin.apt:
        name:
          - vault
