- name: "basicsetup configuration"
  when: enable_basicsetup | default(true)
  block:
    - name: Install basic tools
      become: true
      ansible.builtin.package:
        name: "{{ apt_packages.basic_tools }}"

    - name: Set timezone to Europe/Zurich
      become: true
      community.general.timezone:
        name: Europe/Zurich

    - name: Set locale to en_US.UTF-8
      become: true
      community.general.locale_gen:
        name: en_US.UTF-8

    - name: Set default locale to en_US.UTF-8
      become: true
      ansible.builtin.lineinfile:
        dest: /etc/default/locale
        regexp: "LC_ALL"
        line: 'LC_ALL="en_US.UTF-8"'

    - name: Install additional packages
      become: true
      ansible.builtin.package:
        name: "{{ apt_packages.additional_tools }}"
