---
services:
  open-webui:
    image: "ghcr.io/open-webui/open-webui:v0.8.0"
    container_name: "open-webui"
    ports:
      - "127.0.0.1:13307:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "open-webui:/app/backend/data"
    restart: "unless-stopped"
    environment:
      - "WEBUI_AUTH=False"

volumes:
  "open-webui":
    external: true
